### ISSUE TITLE
Manage opsgenie schedule rotations in `modules/`

### ISSUE THREAD

**Issue by nitrocode** [cloudposse/terraform-opsgenie-incident-management#35]
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Feature

Currently this is managed by `modules/config` but we want to think of a new interface for this in `modules/`.

The [opsgenie_schedule_rotation](https://registry.terraform.io/providers/opsgenie/opsgenie/latest/docs/resources/schedule_rotation) resource can be associated multiple times to a single schedule. Seems like a type of user and team can be used with it.

Current implementation [modules/config/schedule_rotations.tf](https://github.com/cloudposse/terraform-opsgenie-incident-management/blob/master/modules/config/schedule_rotations.tf)

New implementation within [modules/schedule](https://github.com/cloudposse/terraform-opsgenie-incident-management/blob/master/modules/schedule) or in a new submodule called `schedule_rotation`

```yaml
components:
  terraform:
    opsgenie-team-ops:
      metadata:
        component: opsgenie-team
        inherits:
          - opsgenie-team-defaults
      settings:
        spacelift:
          workspace_enabled: true
      vars:
        enabled: true
        name: ops

        schedules:
          minnesota_schedule:
            enabled: false
            description: "Minnesota Schedule"
            timezone: "America/Indianapolis"

            rotations:
              bob_ops:
                # could use the key of the rotation if `name` key is omitted
                name: "bob_ops"
                start_date: "2019-06-18T17:00:00Z"
                end_date: "2019-06-20T17:30:00Z"
                type: "hourly"
                length: 6
                time_restriction:
                  type: "time-of-day"
                  restriction:
                    start_hour: 1
                    start_min: 1
                    end_hour: 10
                    end_min: 1
                participants:
                - type: user
                  user: bob
                - type: team
                  user: ops
```
